/**
 * Re-encrypt a `.mem` file under a different AES key (key-rotation migration primitive).
 *
 * `id` (the only plaintext field) is copied verbatim. Each encrypted payload (`chunks`,
 * `meta`) is decrypted under the old key + its field-bound AAD, then re-encrypted under
 * the new key + the same AAD. New random IVs and tags are generated by AES-GCM each call.
 *
 * `canDecryptMem` is the cheap "already in target state?" probe for resume. Trying one
 * payload is enough: a wrong key fails GCM auth on the first decrypt.
 */
import { decrypt, encrypt, AuthenticationError } from './crypto.js'
import { memAad } from './aad.js'
import type { MemFile } from './types.js'

/**
 * Decrypt both payloads of a MemFile under `oldKey` and re-encrypt under `newKey`,
 * preserving the id and the AAD binding. Returns the new MemFile.
 */
export function reEncryptMem(mem: MemFile, oldKey: Buffer, newKey: Buffer): MemFile {
  // Decrypt with old key (raises AuthenticationError if the key doesn't fit the payload).
  const chunksPlain = decrypt(mem.chunks, oldKey, memAad(mem.id, 'chunks'))
  const metaPlain = decrypt(mem.meta, oldKey, memAad(mem.id, 'meta'))

  // Re-encrypt with new key, same AAD — fresh IV/tag per payload from AES-GCM.
  return {
    id: mem.id,
    chunks: encrypt(chunksPlain, newKey, memAad(mem.id, 'chunks')),
    meta: encrypt(metaPlain, newKey, memAad(mem.id, 'meta')),
  }
}

/**
 * True iff `key` is the right key to decrypt this MemFile. Only checks the `chunks`
 * payload; both payloads share the same key, so one decrypt is sufficient. Returns false
 * on AuthenticationError; any other failure (malformed JSON, missing fields) re-throws
 * because that's not a key mismatch — it's a corrupt file.
 */
export function canDecryptMem(memBytes: Buffer, key: Buffer): boolean {
  // A JSON-parse failure is a corrupt / truncated file, NOT a key mismatch — let it
  // surface (fail-loud) rather than masquerade as "wrong key" to the abort/resume probes.
  const mem = JSON.parse(memBytes.toString('utf8')) as MemFile
  try {
    decrypt(mem.chunks, key, memAad(mem.id, 'chunks'))
    return true
  } catch (e) {
    if (e instanceof AuthenticationError) return false
    throw e
  }
}
